//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Transactions')
export class TransactionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  transactionId: string;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('text', { nullable: true })
  type: string;

  @Column('real', { nullable: true })
  amount: number;

  @Column('text', { nullable: true })
  currency: string;

  @Column('date', { nullable: true })
  dateTime: Date;

  @Column('text', { nullable: true })
  status: string;
}
